export const cssVars = {
  '--h1-font-size': '80px', '--h1-font-style': 'italic', '--h1-font-family': 'var(--font-primary)',
  '--h1-font-weight': 300, '--h1-line-height': '1.2', '--h1-m-font-size': '52px',
  '--h1-letter-spacing': 'normal', '--h1-text-transform': 'none', '--h1-text-decoration': 'none',
  '--h2-font-size': '56px', '--h2-font-style': 'normal', '--h2-font-family': 'var(--font-primary)',
  '--h2-font-weight': 400, '--h2-line-height': '1.2', '--h2-m-font-size': '40px',
  '--h2-letter-spacing': 'normal', '--h2-text-transform': 'none', '--h2-text-decoration': 'none',
  '--h3-font-size': '44px', '--h3-font-style': 'normal', '--h3-font-family': 'var(--font-primary)',
  '--h3-font-weight': 600, '--h3-line-height': '1.2', '--h3-m-font-size': '32px',
  '--h3-letter-spacing': 'normal', '--h3-text-transform': 'none', '--h3-text-decoration': 'none',
  '--h4-font-size': '32px', '--h4-font-style': 'normal', '--h4-font-family': 'var(--font-primary)',
  '--h4-font-weight': 400, '--h4-line-height': '1.2', '--h4-m-font-size': '26px',
  '--h4-letter-spacing': 'normal', '--h4-text-transform': 'none', '--h4-text-decoration': 'none',
  '--h5-font-size': '24px', '--h5-font-style': 'normal', '--h5-font-family': 'var(--font-primary)',
  '--h5-font-weight': 600, '--h5-line-height': '1.2', '--h5-m-font-size': '20px',
  '--h5-letter-spacing': 'normal', '--h5-text-transform': 'none', '--h5-text-decoration': 'none',
  '--h6-font-size': '13px', '--h6-font-style': 'normal', '--h6-font-family': 'var(--font-primary)',
  '--h6-font-weight': 600, '--h6-line-height': '1.5', '--h6-m-font-size': '13px',
  '--h6-letter-spacing': '0.18em', '--h6-text-transform': 'uppercase', '--h6-text-decoration': 'none',
  '--body-font-size': '16px', '--body-font-style': 'normal', '--body-font-family': 'var(--font-secondary)',
  '--body-font-weight': 300, '--body-line-height': '1.5', '--body-m-font-size': '15px',
  '--body-letter-spacing': 'normal', '--body-text-transform': 'normal', '--body-text-decoration': 'none',
  '--font-primary': "'Cormorant Garamond', Georgia, serif",
  '--font-secondary': "'Plus Jakarta Sans', system-ui, sans-serif",
  '--nav-link-color': 'rgb(242, 237, 229)', '--nav-link-font-size': '13px',
  '--nav-link-font-style': 'normal', '--nav-link-color-hover': 'rgb(196, 164, 74)',
  '--nav-link-font-family': 'var(--font-secondary)', '--nav-link-font-weight': 500,
  '--nav-link-line-height': '1.35', '--nav-link-m-font-size': '13px',
  '--nav-link-letter-spacing': '0.06em', '--nav-link-text-transform': 'none',
  '--nav-link-text-decoration': 'none',
  '--body-large-font-size': '19px', '--body-large-font-style': 'normal',
  '--body-large-font-family': 'var(--font-secondary)', '--body-large-font-weight': 400,
  '--body-large-line-height': '1.5', '--body-large-m-font-size': '19px',
  '--body-large-letter-spacing': 'normal', '--body-large-text-transform': 'none',
  '--body-large-text-decoration': 'none',
  '--body-small-font-size': '13px', '--body-small-font-style': 'normal',
  '--body-small-font-family': 'var(--font-secondary)', '--body-small-font-weight': 400,
  '--body-small-line-height': '1.5', '--body-small-m-font-size': '13px',
  '--body-small-letter-spacing': 'normal', '--body-small-text-transform': 'none',
  '--body-small-text-decoration': 'none',
  '--grid-button-primary-font-size': '12px', '--grid-button-primary-padding-x': '32px',
  '--grid-button-primary-padding-y': '14px', '--grid-button-primary-font-style': 'normal',
  '--grid-button-primary-font-family': 'var(--font-secondary)', '--grid-button-primary-font-weight': 500,
  '--grid-button-primary-line-height': 'normal', '--grid-button-primary-m-font-size': '12px',
  '--grid-button-primary-border-radius': '2px', '--grid-button-primary-letter-spacing': '0.08em',
  '--grid-button-primary-text-transform': 'uppercase', '--grid-button-primary-text-decoration': 'none',
  '--grid-button-primary-background-color': 'rgb(200, 92, 58)',
  '--grid-button-primary-background-color-hover': 'rgb(176, 76, 44)',
  '--grid-button-secondary-font-size': '14px', '--grid-button-secondary-padding-x': '40px',
  '--grid-button-secondary-padding-y': '16px', '--grid-button-secondary-font-family': 'var(--font-secondary)',
  '--grid-button-secondary-font-weight': 400, '--grid-button-secondary-border-radius': '2px',
  '--grid-button-secondary-text-transform': 'none', '--grid-button-secondary-background-color': 'transparent',
  '--grid-button-secondary-background-color-hover': 'rgba(139, 105, 20, 0.12)',
}

const heroSrcset = [
  'https://horizons-cdn.hostinger.com/9ff0c242-ec08-4248-b694-3de2ee09bf42/img-20260605-wa0001-E2V4bcFE1sMqHZLZ.jpg?width=375&fit=crop 375w',
  'https://horizons-cdn.hostinger.com/9ff0c242-ec08-4248-b694-3de2ee09bf42/img-20260605-wa0001-E2V4bcFE1sMqHZLZ.jpg?width=768&fit=crop 768w',
  'https://horizons-cdn.hostinger.com/9ff0c242-ec08-4248-b694-3de2ee09bf42/img-20260605-wa0001-E2V4bcFE1sMqHZLZ.jpg?width=1024&fit=crop 1024w',
  'https://horizons-cdn.hostinger.com/9ff0c242-ec08-4248-b694-3de2ee09bf42/img-20260605-wa0001-E2V4bcFE1sMqHZLZ.jpg?width=1440&fit=crop 1440w',
  'https://horizons-cdn.hostinger.com/9ff0c242-ec08-4248-b694-3de2ee09bf42/img-20260605-wa0001-E2V4bcFE1sMqHZLZ.jpg?width=1920&fit=crop 1920w',
  'https://horizons-cdn.hostinger.com/9ff0c242-ec08-4248-b694-3de2ee09bf42/img-20260605-wa0001-E2V4bcFE1sMqHZLZ.jpg?width=2560&fit=crop 2560w',
].join(', ')

export const heroBg = {
  current: 'image',
  src: 'https://horizons-cdn.hostinger.com/9ff0c242-ec08-4248-b694-3de2ee09bf42/img-20260605-wa0001-E2V4bcFE1sMqHZLZ.jpg?width=1440&fit=crop',
  srcset: heroSrcset,
}

export const heroStyle = {
  '--rows': 11, '--width': '1224px', '--row-gap': '16px', '--row-size': '48px', '--column-gap': '24px',
  '--block-padding': '16px 0',
  '--m-block-padding': '120px 16px 120px 16px',
  '--m-grid-template-rows': ' 1fr', '--t-grid-template-rows': ' 1fr',
  '--small-desktop-grid-template-rows': ' 1fr', '--grid-template-rows': ' 1fr',
  '--m-grid-template-columns': '100.00%', '--grid-template-columns': '100.00%',
  '--m-block-min-height': '143px', '--t-block-min-height': '143px',
  '--small-desktop-block-min-height': '59.80392156862745vw', '--block-min-height': '732px',
}
